### ISSUE TITLE
Arguments did not match any overloaded call:

### ISSUE THREAD

**Issue by antoniosapi** [ccrook/QGIS-VectorFieldRenderer-Plugin#10]
Hi Mr Chris Crook,

I am trying to create a vector field with the table you can see in 'Captura1.PNG' and 'Captura2.PNG' as it's showed in 'Captura3.PNG'. But then I get the error in 'Captura4.PNG'. Could you help me to find how to fix it?

Thank you in advance,
Antonio.

<img width="393" alt="Captura1" src="https://github.com/ccrook/QGIS-VectorFieldRenderer-Plugin/assets/136742370/f11da618-b5fd-478b-966c-e3b57de1b53f">
<img width="470" alt="Captura2" src="https://github.com/ccrook/QGIS-VectorFieldRenderer-Plugin/assets/136742370/c31251e6-34e5-4c10-9c24-09f22110fc25">
<img width="513" alt="Captura3" src="https://github.com/ccrook/QGIS-VectorFieldRenderer-Plugin/assets/136742370/a87026df-b27b-4078-ab1a-31499d8fe592">
<img width="471" alt="Captura4" src="https://github.com/ccrook/QGIS-VectorFieldRenderer-Plugin/assets/136742370/6d7c006d-bc5b-47f9-9d62-22aab612ab4b">

**Comment by ccrook** [comment]
Hi.  That is a bug!  I have no idea why it has not shown up before.  I have fixed it in version 1.1.1 of the plugin (I hope).  Thank you for reporting this.

**Comment by antoniosapi** [comment]
Good morning. I have downloaded the new update and it works now. Thank you so much!
